### ISSUE TITLE
Problem when implementing on UITableViewCell

### ISSUE THREAD

**Issue by bigearsenal** [bachonk/InitialsImageView#15]
I have implemented and UIImageView inside a subview on a UITableViewCell.
The InitialsImage didn't show up until I scrolled and cell was reused.
Any ideas?
Thank you!
<img width="803" alt="ảnh" src="https://user-images.githubusercontent.com/6975538/67545599-e89c8a80-f723-11e9-9432-8eccab730f0f.png">
<img width="936" alt="ảnh" src="https://user-images.githubusercontent.com/6975538/67545618-f6eaa680-f723-11e9-8aa4-d1ef5a0fbec6.png">
<img width="936" alt="ảnh" src="https://user-images.githubusercontent.com/6975538/67545630-02d66880-f724-11e9-9dc5-234f83363f67.png">
<img width="987" alt="ảnh" src="https://user-images.githubusercontent.com/6975538/67545642-0ff35780-f724-11e9-9540-c12bf589b354.png">

**Comment by bigearsenal** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6975538/67545830-cb1bf080-f724-11e9-8b73-6757d9d6a909.gif)

**Comment by bachonk** [comment]
That is odd, are you using a `nib` (`.xib` file) for your custom cell?

Great looking app by the way, would love to hear what it is.

**Comment by bigearsenal** [comment]
Hi there!
Thank you 😊.
I'm not using Interface Builder at all.
Perhaps, the frame of imageView wasn't counted at the time setUp was called.
I've tried just setup dummy frame {0,0,100,100} for image before setImageForName and it works :)

**Comment by bachonk** [comment]
Ok great, can I close this out?

**Comment by bigearsenal** [comment]
Hi. Yes. But i think you should make a note in Readme file for notice s.o. who doesn't use interface builder like me.
Thank you )
