### ISSUE TITLE
Swift 4 problem

### ISSUE THREAD

**Issue by gitshell007** [bachonk/InitialsImageView#4]
All its working now with new commit. Thanks

Hi,

With Swift 4 we have a error:

Value of type 'UIImageView' has no member 'setImageForName'

Thanks a lot!

**Comment by assembleMHN** [comment]
I too have this problem, if i set the pod in manage scheme and try to build it, it will fail in a swift 4 project.

**Comment by SuvarnaRatna-DevRabbit** [comment]
Same problem.. Swift4 compilation errors

**Comment by bachonk** [comment]
Check out [v0.2.0](https://github.com/bachonk/InitialsImageView/releases/tag/0.2.0) which should fix this issue!
